id: I66B93BE0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:36:33+00:00'
last_modified: '2022-06-07T12:34:13.532757+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5842
  title: ནང་རིག་པའི་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '1464':
      image_group_id: I1KG5845
      title: ''
      total_pages: 970
      order: 1
      base_file: 1464.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
