id: P000656
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:35.318546
source_metadata:
  id: bdr:W1KG5842
  title: ནང་རིག་པའི་ཚིག་མཛོད།
  author: ''
  volumes:
    9e9e8ef0c56f461eb0957cabca7ff497:
      image_group_id: I1KG5845
      title: ''
      volume_number: 1
      total_pages: 970
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
